default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: user
  #password: postgres

development:
  <<: *default
  database: cajeh_dev

test:
  <<: *default
  database: cajeh_test

production:
  <<: *default
  database: cajeh_prod
